package:
  name: event-model
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  string: {{ environ.get('GIT_BUILD_STR', '') }}py{{ py }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - 'event_model'

about:
  home: https://github.com/NSLS-II/event_model
  license: BSD
